"""add favorite food to users

Revision ID: b06528b792d5
Revises: 
Create Date: 2026-06-10 09:15:23.216425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Il faut donc toujours vérifier le fichier de migration 
# généré avant de l’appliquer.

# revision identifiers, used by Alembic.
revision: str = 'b06528b792d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.add_column('users', sa.Column('favorite_food', sa.String(),
                                nullable=False, server_default="unknown"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_food')
    op.alter_column('posts', 'post',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
